<?php

use Drupal\acsf_acquia_search\HashOverride;

/**
 * @file
 * ACSF Acquia Search module.
 */

 /**
 * Implements hook_acquia_search_get_list_of_possible_cores_alter().
 *
 * @param array $possible_core_ids
 * @param array $context
 */
function acsf_acquia_search_acquia_search_get_list_of_possible_cores_alter(
  array &$possible_core_ids,
  array $context
) {

  // Add "[identifier].[environment].default" as a possible core name.
  $core_name =  $context['identifier'] . '.' . $context['ah_env'] . '.default';
  if (!in_array($core_name, $possible_core_ids)) {
    $possible_core_ids[] = $core_name;
  }

}
